export const initialUsers = [
  {
    name: 'System Administrator',
    email: 'admin@example.com',
    password: 'Admin@123',
    role: 'admin',
    phone: '+1 (555) 019-2834',
    profileImage: '',
  },
  {
    name: 'Sarah Connor',
    email: 'sarah.connor@example.com',
    password: 'Password@123',
    role: 'applicant',
    phone: '+1 (555) 234-5678',
    profileImage: '',
  },
  {
    name: 'Alex Rivera',
    email: 'alex.rivera@example.com',
    password: 'Password@123',
    role: 'applicant',
    phone: '+1 (555) 345-6789',
    profileImage: '',
  },
  {
    name: 'Priya Sharma',
    email: 'priya.sharma@example.com',
    password: 'Password@123',
    role: 'applicant',
    phone: '+1 (555) 456-7890',
    profileImage: '',
  },
];

export const initialProfiles = [
  {
    email: 'sarah.connor@example.com',
    fullName: 'Sarah Connor',
    phone: '+1 (555) 234-5678',
    dateOfBirth: new Date('1996-05-14'),
    gender: 'Female',
    address: '104 Tech Boulevard',
    city: 'San Francisco',
    state: 'CA',
    education: 'B.S. in Computer Science, Stanford University (2018)',
    skills: ['React', 'JavaScript', 'TypeScript', 'Node.js', 'Tailwind CSS', 'Redux'],
    experience: '5+ years building high-traffic Single Page Applications and scalable micro-frontends.',
    resume: 'sample-resume-sarah.pdf',
  },
  {
    email: 'alex.rivera@example.com',
    fullName: 'Alex Rivera',
    phone: '+1 (555) 345-6789',
    dateOfBirth: new Date('1994-11-20'),
    gender: 'Male',
    address: '42 Silicon Avenue',
    city: 'Austin',
    state: 'TX',
    education: 'M.S. in Software Engineering, UT Austin (2017)',
    skills: ['Node.js', 'Express', 'MongoDB', 'PostgreSQL', 'Docker', 'AWS', 'REST APIs'],
    experience: '6 years designing robust backend architectures, distributed data pipelines, and RESTful APIs.',
    resume: 'sample-resume-alex.pdf',
  },
  {
    email: 'priya.sharma@example.com',
    fullName: 'Priya Sharma',
    phone: '+1 (555) 456-7890',
    dateOfBirth: new Date('1998-02-10'),
    gender: 'Female',
    address: '88 Innovation Drive',
    city: 'Seattle',
    state: 'WA',
    education: 'B.Tech in Information Technology, IIT Bombay (2020)',
    skills: ['React', 'Next.js', 'Tailwind CSS', 'Figma', 'UI/UX Design', 'JavaScript'],
    experience: '3.5 years specializing in design systems, accessible frontend experiences, and responsive web apps.',
    resume: 'sample-resume-priya.pdf',
  },
];

export const initialJobs = [
  {
    title: 'Senior React Developer',
    company: 'Acme Tech Solutions',
    description:
      'We are seeking an experienced Senior React Developer to lead our frontend architecture and deliver ultra-responsive, accessible user interfaces for our flagship enterprise SaaS platform.',
    requirements:
      '• 4+ years of professional React and modern JavaScript/TypeScript experience.\n• In-depth expertise in state management, component architecture, and React hooks.\n• Strong understanding of REST APIs, asynchronous programming, and web performance optimization.\n• Experience with Tailwind CSS and design systems.',
    responsibilities:
      '• Architect and build scalable, reusable React components.\n• Collaborate with product designers and backend engineers to integrate RESTful endpoints.\n• Mentor junior frontend engineers and conduct thorough code reviews.\n• Optimize web application performance for maximum speed and scalability.',
    skills: ['React', 'JavaScript', 'TypeScript', 'Tailwind CSS', 'REST APIs'],
    location: 'San Francisco, CA (Hybrid)',
    employmentType: 'Full Time',
    salaryMin: 120000,
    salaryMax: 155000,
    experienceRequired: '4-6 Years',
    educationRequired: "Bachelor's in Computer Science or equivalent",
    vacancies: 2,
    deadline: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000), // 30 days from now
    status: 'Active',
  },
  {
    title: 'Full Stack Node.js Engineer',
    company: 'CloudSphere Innovations',
    description:
      'Join our fast-growing engineering team to build scalable full-stack web applications using Node.js, Express, MongoDB, and React.',
    requirements:
      '• 3+ years experience with Node.js, Express, and MongoDB/Mongoose.\n• Solid proficiency in React.js and modern frontend tooling.\n• Proven track record with JWT authentication, role-based access, and secure API design.\n• Familiarity with Docker and AWS deployment.',
    responsibilities:
      '• Design, develop, and maintain clean, scalable REST APIs.\n• Implement end-to-end features connecting React frontend to MongoDB database.\n• Maintain data security, authentication workflows, and system uptime.\n• Write automated integration and unit tests.',
    skills: ['Node.js', 'Express', 'MongoDB', 'React', 'REST APIs'],
    location: 'Remote',
    employmentType: 'Remote',
    salaryMin: 110000,
    salaryMax: 140000,
    experienceRequired: '3-5 Years',
    educationRequired: "Bachelor's Degree in Computer Science",
    vacancies: 3,
    deadline: new Date(Date.now() + 25 * 24 * 60 * 60 * 1000),
    status: 'Active',
  },
  {
    title: 'UI/UX Designer & Frontend Specialist',
    company: 'PixelCraft Studios',
    description:
      'PixelCraft Studios is looking for a creative UI/UX Designer who loves translating visual wireframes and prototypes into clean, responsive Tailwind and React components.',
    requirements:
      '• 2+ years of UI/UX design and frontend development experience.\n• Deep proficiency in Figma, design systems, and component libraries.\n• Hands-on coding skills in React, HTML5, modern CSS/Tailwind.\n• Excellent eye for typography, layout hierarchy, and micro-animations.',
    responsibilities:
      '• Craft intuitive user journeys, wireframes, and high-fidelity Figma mockups.\n• Develop pixel-perfect, accessible React components matching approved designs.\n• Conduct usability testing and iterate based on customer feedback.\n• Maintain company-wide design tokens and documentation.',
    skills: ['Figma', 'UI/UX Design', 'React', 'Tailwind CSS', 'CSS3'],
    location: 'Austin, TX',
    employmentType: 'Full Time',
    salaryMin: 90000,
    salaryMax: 115000,
    experienceRequired: '2-4 Years',
    educationRequired: "Degree in Design, HCI, or Computer Science",
    vacancies: 1,
    deadline: new Date(Date.now() + 18 * 24 * 60 * 60 * 1000),
    status: 'Active',
  },
  {
    title: 'Backend Systems Engineer',
    company: 'DataPulse Labs',
    description:
      'We are looking for a Backend Systems Engineer to architect high-throughput data pipelines, database schema optimization, and microservice APIs.',
    requirements:
      '• Strong proficiency in Node.js, Express, MongoDB aggregation pipelines, and SQL.\n• Experience designing distributed caching strategies with Redis.\n• Understanding of message queues (RabbitMQ/Kafka) and system reliability engineering.',
    responsibilities:
      '• Optimize database queries and aggregation pipelines for sub-100ms latency.\n• Implement secure data models and multi-tenant access controls.\n• Monitor server health, API performance, and error budgets.\n• Troubleshoot production performance bottlenecks.',
    skills: ['Node.js', 'Express', 'MongoDB', 'Redis', 'Docker'],
    location: 'Seattle, WA (Hybrid)',
    employmentType: 'Full Time',
    salaryMin: 125000,
    salaryMax: 160000,
    experienceRequired: '4-7 Years',
    educationRequired: "Bachelor's or Master's in Computer Science",
    vacancies: 2,
    deadline: new Date(Date.now() + 20 * 24 * 60 * 60 * 1000),
    status: 'Active',
  },
  {
    title: 'DevOps & Cloud Infrastructure Engineer',
    company: 'Apex Networks',
    description:
      'Apex Networks is hiring a DevOps Engineer to automate CI/CD pipelines, manage Kubernetes clusters, and maintain secure multi-region cloud infrastructure.',
    requirements:
      '• 3+ years experience with AWS/GCP, Docker, and Kubernetes.\n• Proficiency with CI/CD tools (GitHub Actions, GitLab CI) and Terraform.\n• Strong background in Linux administration and network security.',
    responsibilities:
      '• Build and maintain automated build, test, and deployment workflows.\n• Ensure 99.99% system availability and implement zero-downtime deployments.\n• Enforce infrastructure security, SSL management, and IAM policies.',
    skills: ['AWS', 'Docker', 'Kubernetes', 'CI/CD', 'Terraform'],
    location: 'Remote',
    employmentType: 'Contract',
    salaryMin: 130000,
    salaryMax: 170000,
    experienceRequired: '3-6 Years',
    educationRequired: "Bachelor's in Engineering or related field",
    vacancies: 1,
    deadline: new Date(Date.now() + 15 * 24 * 60 * 60 * 1000),
    status: 'Active',
  },
  {
    title: 'Junior Frontend Developer Intern',
    company: 'Nova Dynamics',
    description:
      'Exciting 6-month internship opportunity for passionate aspiring frontend developers. Gain hands-on mentorship building live web applications with modern tech stacks.',
    requirements:
      '• Strong fundamentals in HTML, CSS, JavaScript, and React basics.\n• Eager to learn, passionate about clean code, and good communication skills.\n• Current student or recent graduate in Computer Science or related bootcamp.',
    responsibilities:
      '• Assist senior engineers in building UI components and bug fixing.\n• Participate in daily standups, code reviews, and sprint planning.\n• Write clean, commented, and well-tested code.',
    skills: ['JavaScript', 'React', 'HTML5', 'CSS3', 'Git'],
    location: 'Boston, MA',
    employmentType: 'Internship',
    salaryMin: 45000,
    salaryMax: 60000,
    experienceRequired: '0-1 Years',
    educationRequired: "Enrolled in or completed Bachelor's Degree",
    vacancies: 2,
    deadline: new Date(Date.now() + 40 * 24 * 60 * 60 * 1000),
    status: 'Active',
  },
  {
    title: 'Legacy Systems Maintenance Lead',
    company: 'OldWorld Enterprise',
    description: 'Archived job posting for legacy application maintenance.',
    requirements: 'COBOL, PHP, Java 7',
    responsibilities: 'Maintain legacy systems.',
    skills: ['PHP', 'Java', 'SQL'],
    location: 'Chicago, IL',
    employmentType: 'Full Time',
    salaryMin: 80000,
    salaryMax: 95000,
    experienceRequired: '5+ Years',
    educationRequired: "Bachelor's Degree",
    vacancies: 1,
    deadline: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000), // Expired 5 days ago
    status: 'Closed',
  },
];
